name: Bond Yield Crawler

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at 00:00
  workflow_dispatch:  # Allow manual trigger

jobs:
  crawl:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run bond yield crawler
      run: python crawler/bond_yield_crawler.py
      
    - name: Commit changes if new data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/raw/jp_bond_yield.csv data/raw/vn_bond_yield.csv data/cleaned/jp_bond_yield_cleaned.csv data/cleaned/vn_bond_yield_cleaned.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update bond yield data [skip ci]" && git push)
        
    - name: Store data to cloud
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        python store_data/jp_bond_yield_store_data.py
        python store_data/vn_bond_yield_store_data.py 