name: VN Interbank Interest Rate Crawler

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  

jobs:
  crawl:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run crawler
      run: |
        python -m crawler.vn_interbank_interest_crawler
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data/ visualize/images/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update VN interbank interest rate data and visualizations"
          git push
        fi 

    - name: Store data to cloud
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: python store_data/vn_interbank_store_data.py 